appId: dev.theolm.rinku.decompose
env:
  appId: dev.theolm.rinku.decompose
  host: dev.theolm.rinku.decompose

---
# Fresh open of the app
- stopApp: ${appId}
- runFlow:
      file: subflows/deeplink-query-flow.yaml
      env:
          appId: ${appId}
          host: ${host}
# Internal deeplink with the app open
- runFlow:
    file: subflows/deeplink-query-flow.yaml
    env:
      appId: ${appId}
      host: ${host}

# Another run with cold boot
- stopApp: ${appId}
- runFlow:
    file: subflows/deeplink-query-flow.yaml
    env:
      appId: ${appId}
      host: ${host}